package Activities.hassan.JAVA.Youtube.Day18_Exeption;

public class test2 {
    public static void main(String[] args) throws InterruptedException {


        //1) ArithmeticException

//       try {
//           System.out.println(100/number);
//       }
//
//      catch (Exception  e)
//      {
//          System.out.println("invalid data");
//      }


        System.out.println("program is completed");


Object x=new int [5];



    }
}
